

# Configs for training.


---
# dataset options:
dataset:
  image_dataset_dir: "/proj/systewar/datasets/IMAC/image_dataset"
  audio_dataset_dir: "/proj/systewar/datasets/audioset_music_mood"
  train_n_batches: 100     # number of batches (per epoch) to use for training set
  val_n_batches: 100        # number of batches to use for validation set
  sample_rate: 16000
  random_seed: 42

# data augmentation options:
audio_augment:
  n_views: 2
  gaussian_noise:
    prob: 0.8
    min_snr: 5.0      # in dB
    max_snr: 40.0     # in dB
  background_noise:
    sounds_path: "/proj/systewar/datasets/NSynth/nsynth-train/audio"
    prob: 0.8
    min_snr: 3.0      # in dB
    max_snr: 30.0     # in dB
image_augment:
  n_views: 2     # currently must be equal to n_views of audio_augment

# audio backbone options:
audio_backbone:
  model_name: "HarmonicCNN"      # or "ShortChunk" or "SampleCNN" or "CLAP"
  pretrained_model_paths:
    HarmonicCNN: "/proj/systewar/pretrained_models/music_tagging/msd/harmonic_cnn/best_model.pth"
    ShortChunk: "/proj/systewar/pretrained_models/music_tagging/msd/short_chunk_resnet/best_model.pth"
    SampleCNN: "/proj/systewar/pretrained_models/VCMR/multimodal/multimodal_model_1.ckpt"
    CLAP: "/project/shrikann_35/tiantiaf/music/music/pretrained_models/music_speech_epoch_15_esc_89.25.pt"
  last_layer_embed: "layer7"     # only used for "ShortChunk" and "HarmonicCNN"
  pool_type: "max"               # # only used for "ShortChunk" and "HarmonicCNN"

# full model options:
full_model:
  multi_task: false
  output_embed_dim: 128
  base_proj_hidden_dim: 256
  base_proj_dropout: 0.2
  base_proj_output_dim: 128
  task_proj_dropout: 0.5
  normalize_image_embeds: true
  normalize_audio_embeds: true
  freeze_image_backbone: true
  freeze_audio_backbone: true

# training options:
training:
  loss_temperature: 0.07     # TODO: Maybe try in range [0.1, 0.3]
  loss_weights:
    image2image: 0.25
    audio2audio: 0.25
    image2audio: 0.25
    audio2image: 0.25
  batch_size: 64
  max_epochs: 30
  optimizer: "AdamW"
  learn_rate: 0.0001
  val_check_interval: 1.0     # how often to check validation set within a single training epoch
  n_workers: 4
  gpu: 1

# logging options:
# note: logs are saved to log_dir/experiment_name/experiment_version/
logging:
  log_dir: "train_logs"
  experiment_name: null     # automatically creates an experiment name if set to null (recommended)
  experiment_version: null     # automatic versioning if set to null (recommended)
  log_every_n_steps: 20     # how often to log
...

