

# Configs for cross-modal retrieval evaluation.


---
# dataset options:
dataset:
  subset: "test"     # or "test"
  image_dataset_dir: "/content/drive/MyDrive/LIKELION/EmoCLIM-dataset/DeepEmotion"
  audio_dataset_dir: "/content/drive/MyDrive/LIKELION/EmoCLIM-dataset/AudioSet"
  sample_rate: 48000     # or 16000

# audio backbone options:
audio_backbone:
  model_name: "CLAP"      # or "HarmonicCNN" or "ShortChunk" or "SampleCNN"
  last_layer_embed: "layer7"
  pool_type: "max"

# full model options:
full_model:
  checkpoint_path: "/content/drive/MyDrive/LIKELION/EmoCLIM-dataset/train_logs/single_task/CLAP/frozen/all_losses/version_1/checkpoints/last.ckpt"
  multi_task: false
  output_embed_dim: 128
  base_proj_hidden_dim: 256
  base_proj_dropout: 0.2     # TODO: Probably can remove this.
  base_proj_output_dim: 128
  task_proj_dropout: 0.5     # TODO: Probably can remove this.
  normalize_image_embeds: true
  normalize_audio_embeds: true
  freeze_image_backbone: true     # TODO: Probably can remove this.
  freeze_audio_backbone: true     # TODO: Probably can remove this.

# evaluation options:
eval:
  results_dir: null     # automatically sets results directory if set to null (recommended)
  loss_weights_mode: "all_losses"     # necessary for automatic results directory naming
  overlap_ratio: 0.75
  retrieval_metrics: ["precision", "MRR"]
  k_vals: [1, 5,]
  gpu: 0 #1
...

