

# Contains categories of the top-50 tags for the MagnaTagATune dataset.


---
genre: [classical, techno, electronic, rock, indian, opera, pop, classic, new age, dance, country, metal]
mood: [slow, fast, ambient, loud, quiet, soft, weird]
instrument: [guitar, strings, drums, piano, violin, synth, harpsichord, flute, sitar, harp, cello]
vocals: [vocal, female, male, singing, vocals, no vocals, no vocal, man, voice, male voice, female vocal, female voice]
other: [beat, solo, beats, choir, choral]
...

